### ISSUE TITLE
Secure Reply to All context menu issues

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#5928]
From customer:
  
> - The single reply icon appears instead of "Reply to All" when selecting "Reply to All" from the three-dot menu, but the recipients are correctly listed  when an external recipient is involved.
>  - In an email with both external and internal recipients, in the first reception the internal recipient does not see all recipients in the interface. > As a result, the "Reply to All" option is missing from the three-dot menu, although "Secure Reply to All" is available at the bottom.
>  - Choosing "Reply to All" from the three-dot menu results in a single reply instead of replying to all recipients when only internal users are in the loop.

**Comment by sosnovsky** [comment]
Hi @martgil, do you have any progress on this issue?

> In an email with both external and internal recipients, in the first reception the internal recipient does not see all recipients in the interface. > As a result, the "Reply to All" option is missing from the three-dot menu, although "Secure Reply to All" is available at the bottom.

This one seems to be a bit complicated as it'll probably require parsing of `reply-to` header for the message, to show `secure reply all` button. What about moving it to separate issue and let Ioan work on it?

**Comment by martgil** [comment]
@sosnovsky - it is now available at https://github.com/FlowCrypt/flowcrypt-browser/issues/5933

**Comment by sosnovsky** [comment]
Hi @martgil, let's work on fixing these issues to make a small bugfix release next week. Thanks!

**Comment by martgil** [comment]
Thanks, Roma. I'll do my best to meet the deadline and work on improving the reported issues.

**Comment by sosnovsky** [comment]
@martgil feel free to message me if you'll stuck with any issues.

**Comment by martgil** [comment]
Thanks @sosnovsky for offering your helping hand as always. I've already fixed the 3rd issue (if we refer to the unlisted order above) and already adding a test case for it.

As per "The single reply icon appears instead of "Reply to All" when selecting "Reply to All" from the three-dot menu, but the recipients are correctly listed when an external recipient is involved." - I'm having some trouble with it reproducing it, have you been able to replicate it on your end?

**Comment by martgil** [comment]
I think the points 1 and 3 from the unordered list above gets covered by the PR #5934

**Comment by sosnovsky** [comment]
> I think the points 1 and 3 from the unordered list above gets covered by the PR [#5934](https://github.com/FlowCrypt/flowcrypt-browser/pull/5934)

Were you able to replicate both of them or still having trouble with `The single reply icon appears instead of "Reply to All" when selecting "Reply to All" from the three-dot menu`?

**Comment by martgil** [comment]
It's just I'm still unable to replicate `The single reply icon appears instead of "Reply to All" when selecting "Reply to All" from the three-dot menu`. Not sure what I'm doing wrong. Though, I observed that point 1 is issue co-related to point 3 since the icon will default to reply only due to the bug, therefore the icon will also persist as "reply" icon instead of "reply-all". Either way, I'm not so sure if that's what point 1 really means.

**Comment by sosnovsky** [comment]
Point 3 `Choosing "Reply to All" from the three-dot menu results in a single reply instead of replying to all recipients when only internal users are in the loop.` still reproducible for me in https://github.com/FlowCrypt/flowcrypt-browser/pull/5934

Open encrypted message with multiple recipients and click `secure reply all` button in 3-dots message actions menu.
Secure compose box will have only single recipient instead of full recipients list.

**Comment by martgil** [comment]
Thanks for checking Point 3 @sosnovsky  - For me it is fixed when using https://github.com/FlowCrypt/flowcrypt-browser/pull/5934 build and looks something like this:

https://github.com/user-attachments/assets/d9d66346-0d17-44e1-9944-ce582f9c3ace

Sometimes, after running `npm run build` I go to `chrome://extensions` do refresh the debug extension in order to the old code to fresh. Please kindly retry checking it again.

**Comment by sosnovsky** [comment]
I tried to rebuild and reload extension and now issue is fixed, seems like it was using older `master` build so all good here, thanks!
Just a minor thing - let's change button text from `Secure Reply All` to `Secure Reply to All` to be consistent with Google button and with our other secure buttons.

**Comment by martgil** [comment]
Thanks for your confirmation @sosnovsky - Btw, I've reached out with the customers to check the debug build I've prepared and they confirmed that the issue 1 and 3 does not exists there anymore. 

> Just a minor thing - let's change button text from Secure Reply All to Secure Reply to All to be consistent with Google button and with our other secure buttons.

I have overlooked this one and indeed it should be consistently written as "Secure Reply to All". I've corrected this via a small refactor.
